Repository cri-o/crio-credential-provider, pull requests merged in 2025-09, with the labels that each got.

#4 Add OWNERS file
  OWNERS
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#10 Modularize whole project into dedicated go packages
  .github/workflows/ci.yml
  .golangci.yml
  .typos.toml
  Makefile
  cmd/credential-provider/main.go
  internal/pkg/app/app.go
  internal/pkg/auth/auth.go
  internal/pkg/auth/auth_test.go
  internal/pkg/config/config.go
  internal/pkg/docker/docker.go
  internal/pkg/k8s/k8s.go
  internal/pkg/logger/logger.go
  internal/pkg/mirrors/mirrors.go
  internal/pkg/mirrors/mirrors_test.go
  main.go
Labels: dco-signoff: yes, release-note-none, lgtm, approved

#12 Fix logic handling global auth and registry matching
  go.mod
  go.sum
  internal/pkg/auth/auth.go
  internal/pkg/auth/auth_test.go
  internal/pkg/docker/docker.go
  internal/pkg/mirrors/mirrors_test.go
Labels: dco-signoff: yes, release-note-none, lgtm, approved, kind/feature

#11 Add basic e2e test
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  Makefile
  README.md
  dependencies.yaml
  internal/pkg/app/app.go
  test/cluster/credential-provider-config.yml
  test/cluster/pod.yml
  test/cluster/rbac.yml
  test/cluster/secret.yml
  test/e2e-run
  test/e2e-setup
Labels: dco-signoff: yes, release-note-none, lgtm, approved

#13 Use testify/assert instead of tj/assert
  go.mod
  go.sum
  internal/pkg/auth/auth_test.go
  internal/pkg/mirrors/mirrors_test.go
Labels: dco-signoff: yes, release-note-none, lgtm, approved, kind/cleanup

#14 Add unit tests to k8s package
  internal/pkg/k8s/k8s.go
  internal/pkg/k8s/k8s_test.go
Labels: dco-signoff: yes, release-note-none, lgtm, approved

#20 Create first `app` package unit test
  cmd/credential-provider/main.go
  internal/pkg/app/app.go
  internal/pkg/app/app_test.go
  internal/pkg/k8s/k8s.go
Labels: dco-signoff: yes, release-note-none, lgtm, approved

#27 Update golangci-lint and config
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/pkg/auth/auth_test.go
  internal/pkg/mirrors/mirrors_test.go
Labels: dco-signoff: yes, release-note-none, lgtm, approved
